### ISSUE TITLE
Can not get bluetooth device list

### ISSUE THREAD

**Issue by yk-e** [NordicID/nur_sdk#27]
Hello,

I try to use NurSdk for react native application. I need deviceList as an ArrayList. Current structure starts a new activity and shows a UI but a react native application runs in a single activity. I tried to call getDeviceList() method in NurDeviceScanner class but no result returns. I debug into the code and find out that inside the BleScanner.queryBLEDevices() method, no device is added to the list. Because the mDeviceList is empty, I cant connec to the right reader. 

How can I get the bluetooth device list near?

Thanks in advance.

**Comment by mikkonid** [comment]
Hi,

Not sure why it's not working. Did you call BleScanner.init() ?

BleScanner code is available here:
https://github.com/NordicID/nur_nurapi_android/blob/master/NurApiAndroid/src/main/java/com/nordicid/nurapi/BleScanner.java

Maybe you can modify it for your needs.

**Comment by yk-e** [comment]
Yes, I call init. This is my initiation method:

@Override
    public void initiateRfidIntegration(RfidModule rfidModule) {
        this.context = rfidModule;
        if (deviceScanner == null){
            mNurApi = new NurApi();
            mNurApi.setListener(mNurApiListener);
            BleScanner.init(context.getApplicationContext());
            deviceScanner = new NurDeviceScanner(context.getApplicationContext(), 7, deviceScannerListener, mNurApi);
        }
        if (availableRFIDReaderList == null) {
            deviceScanner.queryBLEDevices();
            new NordicIDRfidHandler.CreateInstanceTask().execute();
        }
    }

**Comment by mikkonid** [comment]
Try call deviceScanner.scanDevices() instead of queryBLEDevices()

scanDevices sets mScanning flag to true, which allows addDevice() method to add device to list.
https://github.com/NordicID/nur_nurapi_android/blob/d1f4c13286a3a613dc9e57cd902bc7f905f39a95/NurApiAndroid/src/main/java/com/nordicid/nurapi/NurDeviceScanner.java#L83
https://github.com/NordicID/nur_nurapi_android/blob/d1f4c13286a3a613dc9e57cd902bc7f905f39a95/NurApiAndroid/src/main/java/com/nordicid/nurapi/NurDeviceScanner.java#L171

**Comment by yk-e** [comment]
Ok, will try that. I think it is about the NurDeviceScannerListener initilization. 
I'll update here.
Thanks for now!

**Comment by yk-e** [comment]
If you implement NurDeviceScanner.NurDeviceScannerListener class the problem is solved. Thanks for the help again.
